
name: GitHub Actions Demo
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Touch secret env
        run: |
          touch .env
          echo ${{ secrets.XKEY }} >> .env
      - name: Install Dependencies
        run: yarn
      - name: App Build
        run: yarn build
      - name: Echo status
        run: echo "ğŸ This job's status is ${{ job.status }}."
